export const UPDATE_CHAT_PANEL = "UPDATE_CHAT_PANEL";
export const CHANGE_MESSAGE_HISTORY_TOKEN = "CHANGE_MESSAGE_HISTORY_TOKEN";
export const SET_CONVERSATION_TOKEN = "SET_CONVERSATION_TOKEN";
export const SET_USER_ID = "SET_USER_ID";
export const SET_ONLINE_USER = "SET_ONLINE_USER";
export const UPDATE_USER_LAST_MESSAGE_ON_CHAT_PANEL =
  "UPDATE_USER_LAST_MESSAGE_ON_CHAT_PANEL";
export const CHANGE_NEW_MESSAGE_CLASS = "CHANGE_NEW_MESSAGE_CLASS";
export const UPDATE_MESSAGE_HISTORY = "UPDATE_MESSAGE_HISTORY";
